import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync,spawn} from 'node:child_process';
import {serviceLease} from '../lib/backup-service.mjs';
import {captureWorkingTree} from '../lib/working-tree-backup.mjs';
import {newRecoveryTarget,remap,assertNoProduction,sandboxArgs} from '../lib/recovery-isolation.mjs';
const tmp=()=>fs.mkdtempSync('/tmp/kurumi-recovery-test-');
function mock(initial,failStart=false){let state=initial;const calls=[];const run=(_cmd,args)=>{if(args.includes('show'))return {status:0,stdout:state};if(args.includes('stop')){calls.push('stop');state='inactive';return {status:0};}if(args.includes('start')){calls.push('start');if(failStart)return {status:1};state='active';return {status:0};}throw Error('unexpected');};return {run,calls};}
test('backup restores only the service it stopped; cleanup is idempotent',()=>{const m=mock('active');const l=serviceLease(m);l.stop();assert(l.quiesced);l.restore();l.restore();assert.deepEqual(m.calls,['stop','start']);const n=mock('inactive');const idle=serviceLease(n);idle.stop();assert(idle.quiesced);idle.restore();assert.deepEqual(n.calls,[]);});
test('ambiguous service transition and failed restart do not pass',()=>{assert.throws(()=>serviceLease(mock('activating')).stop(),/transition/);const l=serviceLease(mock('active',true));l.stop();assert.throws(()=>l.restore(),/restart failed/);});
for(const signal of ['SIGINT','SIGTERM','SIGHUP'])test(`backup ${signal} restores service and exits nonzero`,async()=>{
 const dir=tmp(),log=dir+'/calls';const module=new URL('../lib/backup-service.mjs',import.meta.url).href;
 const src=`import fs from 'node:fs';import {serviceLease,installBackupExitHandlers} from ${JSON.stringify(module)};let active=true;const l=serviceLease({run:(c,a)=>{if(a.includes('show'))return {status:0,stdout:active?'active':'inactive'};const op=a.includes('stop')?'stop':'start';fs.appendFileSync(${JSON.stringify(log)},op+'\\n');active=op==='start';return {status:0};}});installBackupExitHandlers(l);l.stop();console.log('ready');setInterval(()=>{},1000);`;
 const c=spawn(process.execPath,['--input-type=module','-e',src],{stdio:['ignore','pipe','pipe']});const done=new Promise(resolve=>c.on('exit',(code,signal)=>resolve({code,signal})));await new Promise(resolve=>c.stdout.once('data',resolve));c.kill(signal);const r=await done;assert(r.code>0);assert.deepEqual(fs.readFileSync(log,'utf8').trim().split('\n'),['stop','start']);fs.rmSync(dir,{recursive:true});
});
test('working tree survives mixed text/binary edits, deletions, renames and Chinese untracked paths',()=>{
 const dir=tmp(),src=dir+'/src',dest=dir+'/out',bk=dir+'/backup';fs.mkdirSync(src);fs.mkdirSync(bk);
 const run=(cwd,cmd,args)=>{const r=spawnSync(cmd,args,{cwd,encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r.stdout;};
 run(src,'git',['init','-q']);for(const [n,v] of [['文字.txt','before\n'],['edit.bin','old\0'],['delete.bin','delete\0'],['rename.bin','rename\0']])fs.writeFileSync(src+'/'+n,v);
 run(src,'git',['add','.']);run(src,'git',['-c','user.name=Test','-c','user.email=test@localhost','commit','-qm','fixture']);run(dir,'git',['clone','-q',src,dest]);
 fs.writeFileSync(src+'/文字.txt','after\n');fs.writeFileSync(src+'/edit.bin','new\0');fs.unlinkSync(src+'/delete.bin');fs.renameSync(src+'/rename.bin',src+'/重命名.bin');run(src,'git',['add','-A']);fs.writeFileSync(src+'/未跟踪文件','untracked');
 captureWorkingTree(src,bk,'repo');run(dest,'git',['apply',bk+'/repo-uncommitted.patch']);run(dest,'tar',['-xf',bk+'/repo-untracked.tar']);
 const files=fs.readdirSync(src).filter(x=>x!=='.git').sort();assert.deepEqual(fs.readdirSync(dest).filter(x=>x!=='.git').sort(),files);for(const f of files)assert.deepEqual(fs.readFileSync(src+'/'+f),fs.readFileSync(dest+'/'+f));fs.rmSync(dir,{recursive:true});
});
test('recovery target cannot reuse a populated directory or a symlink',()=>{const dir=tmp();assert.throws(()=>newRecoveryTarget(dir));fs.symlinkSync(dir,dir+'-link');assert.throws(()=>newRecoveryTarget(dir+'-link'));assert.throws(()=>newRecoveryTarget('/home/afrangry/recovery'));fs.unlinkSync(dir+'-link');fs.rmSync(dir,{recursive:true});});
test('all config branches and project registry roots remap, unknown production references fail',()=>{const cfg={agents:{workspace:'/home/afrangry/.openclaw-fusion/workspace'},runner:'/home/afrangry/kurumi-fusion/plugin',fixtures:[{source:'/home/afrangry/.openclaw-fusion/check'}]};const got=remap(cfg,'/tmp/r/runtime','/tmp/r/repo');assertNoProduction(got);assert.equal(got.runner,'/tmp/r/repo/plugin');assert.throws(()=>assertNoProduction({command:'node /home/afrangry/kurumi-fusion/run.js'}));});
test('sandbox cannot see host canary or production and has a different network namespace',()=>{const dir=tmp(),host=tmp();fs.writeFileSync(host+'/canary','outside');const net=fs.readlinkSync('/proc/self/ns/net');const code=`const fs=require('fs'),a=require('assert/strict');a(!fs.existsSync(${JSON.stringify(host+'/canary')}));a(!fs.existsSync('/home/afrangry/.openclaw-fusion'));a.notEqual(fs.readlinkSync('/proc/self/ns/net'),${JSON.stringify(net)});`;const r=spawnSync('bwrap',[...sandboxArgs(dir),'/usr/bin/node','-e',code],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);fs.rmSync(dir,{recursive:true});fs.rmSync(host,{recursive:true});});
test('legacy rollback requires one explicit choice and prints only its startup path',()=>{const script=new URL('../restore-legacy.sh',import.meta.url).pathname;const missing=spawnSync('bash',[script,'--restore'],{encoding:'utf8'});assert.equal(missing.status,2);for(const choice of ['A','B']){const r=spawnSync('bash',[script,'--restore','--system',choice],{encoding:'utf8',maxBuffer:4*1024*1024});assert.equal(r.status,0,r.stderr);if(choice==='A'){assert.match(r.stdout,/systemctl --user start openclaw-gateway.service/);assert(!r.stdout.includes('systemctl --user start qq-bridge.service'));}else{assert.match(r.stdout,/systemctl --user start qq-bridge.service/);assert.match(r.stdout,/start snowluma.service snowluma-qq.service/);assert(!r.stdout.includes('systemctl --user start openclaw-gateway.service'));}}});
